#!/usr/bin/env python3
"""
Pull PostHog metrics for the homepage→waitlist funnel and post-signup
share/viral mechanics. Writes a markdown report to `.tmp/`.

Reads from `.env`:
    POSTHOG_PERSONAL_API_KEY=phx_...     # Personal API key, NOT the public ph_
    POSTHOG_PROJECT_ID=167453
    POSTHOG_HOST=https://eu.posthog.com  # optional, defaults to EU cloud

Usage:
    python tools/posthog_metrics.py                         # last 30 days
    python tools/posthog_metrics.py --window 7d
    python tools/posthog_metrics.py --window 30d --focus share

If credentials are missing or the API errors out, the tool writes a stub
report with `metrics: unavailable` so the audit workflows can continue with
qualitative-only inputs.

Stdlib only.
"""
from __future__ import annotations

import argparse
import datetime as _dt
import json
import os
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
ENV_PATH = PROJECT_ROOT / ".env"
DEFAULT_HOST = "https://eu.posthog.com"
DEFAULT_WINDOW = "30d"


def load_env(path: Path) -> dict[str, str]:
    """Tiny .env loader. No quoting magic, no shell expansion. Just KEY=VALUE."""
    env: dict[str, str] = {}
    if not path.exists():
        return env
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        env[key.strip()] = value.strip().strip("'").strip('"')
    return env


def parse_window(window: str) -> int:
    """'7d' → 7, '30d' → 30. Days only — that's the only granularity audits
    care about."""
    m = re.fullmatch(r"(\d+)d", window.strip().lower())
    if not m:
        raise ValueError(f"Invalid --window: {window!r}. Expected e.g. '7d', '30d'.")
    return int(m.group(1))


class PostHogClient:
    def __init__(self, host: str, project_id: str, api_key: str):
        self.host = host.rstrip("/")
        self.project_id = project_id
        self.api_key = api_key

    def query(self, hogql: str) -> dict:
        url = f"{self.host}/api/projects/{self.project_id}/query/"
        body = json.dumps({"query": {"kind": "HogQLQuery", "query": hogql}}).encode()
        req = urllib.request.Request(
            url,
            data=body,
            headers={
                "Authorization": f"Bearer {self.api_key}",
                "Content-Type": "application/json",
            },
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=30) as resp:
            return json.loads(resp.read().decode())


def safe_query(client: PostHogClient, hogql: str) -> tuple[list, str | None]:
    """Run a HogQL query, return (results, error_or_None)."""
    try:
        data = client.query(hogql)
        return data.get("results", []), None
    except urllib.error.HTTPError as e:
        body = ""
        try:
            body = e.read().decode()[:200]
        except Exception:
            pass
        return [], f"HTTP {e.code}: {body}"
    except urllib.error.URLError as e:
        return [], f"URL error: {e.reason}"
    except (json.JSONDecodeError, KeyError, TimeoutError) as e:
        return [], f"{type(e).__name__}: {e}"


def fmt_count(rows: list) -> int:
    """Pull the first scalar out of a [[N]] result. Defaults to 0."""
    if not rows:
        return 0
    first = rows[0]
    if not first:
        return 0
    return int(first[0] or 0)


def render_report(
    window_days: int,
    focus: str | None,
    metrics: dict,
    errors: list[str],
) -> str:
    today = _dt.date.today().isoformat()
    lines: list[str] = []
    lines.append(f"# PostHog Metrics — {today} ({window_days}-day window)\n")
    lines.append(
        "Generated by `tools/posthog_metrics.py`. Consumed by the audit "
        "workflows in `workflows/`.\n"
    )

    if errors:
        lines.append("\n> **Partial data** — one or more queries failed:\n")
        for err in errors:
            lines.append(f"> - {err}\n")
        lines.append("")

    if metrics.get("_unavailable"):
        lines.append(
            "\n## metrics: unavailable\n\n"
            "PostHog credentials missing or all queries failed. Audit workflow "
            "should fall back to qualitative-only analysis.\n"
        )
        return "\n".join(lines)

    lines.append("\n## Funnel — homepage → waitlist signup\n")
    lines.append("| Stage | Count | Conversion to next |")
    lines.append("|---|---|---|")
    homepage_views = metrics.get("homepage_pageviews", 0)
    waitlist_views = metrics.get("waitlist_pageviews", 0)
    signups = metrics.get("signups", 0)
    duplicates = metrics.get("duplicate_signups", 0)
    referral_signups = metrics.get("referral_signups", 0)

    def pct(num: int, denom: int) -> str:
        if not denom:
            return "—"
        return f"{(100 * num / denom):.1f}%"

    lines.append(f"| Homepage views | {homepage_views} | {pct(waitlist_views, homepage_views)} |")
    lines.append(f"| Waitlist views | {waitlist_views} | {pct(signups, waitlist_views)} |")
    lines.append(f"| Signups | {signups} | — |")
    lines.append(f"| Duplicate-signup attempts | {duplicates} | — |")

    lines.append("\n## Share funnel (post-signup)\n")
    share_clicks_total = metrics.get("share_clicks_total", 0)
    share_by_channel: dict[str, int] = metrics.get("share_clicks_by_channel", {})
    share_copy_ok = metrics.get("share_copy_succeeded", 0)
    share_native_ok = metrics.get("share_native_completed", 0)

    lines.append("| Stage | Count |")
    lines.append("|---|---|")
    lines.append(f"| Signups | {signups} |")
    lines.append(f"| `share_clicked` (any channel) | {share_clicks_total} |")
    for ch in ("native", "whatsapp", "email", "copy", "twitter"):
        lines.append(f"| `share_clicked` ({ch}) | {share_by_channel.get(ch, 0)} |")
    lines.append(f"| `share_copy_succeeded` | {share_copy_ok} |")
    lines.append(f"| `share_native_completed` | {share_native_ok} |")
    lines.append(f"| Signups with `referred_by` set | {referral_signups} |")

    intent_rate = pct(share_clicks_total, signups)
    realised_k = (referral_signups / signups) if signups else 0
    lines.append(f"\n- **Share-intent rate** (share_clicked ÷ signups): {intent_rate}")
    lines.append(f"- **Realised viral coefficient** (referrer-attributed signups ÷ signups): {realised_k:.3f}")

    if focus == "share" and share_clicks_total < 20:
        lines.append(
            "\n> **Volume note** — fewer than 20 `share_clicked` events in window. "
            "Treat the breakdown as directional, not statistical. The audit should "
            "flag this and weight qualitative inputs more heavily.\n"
        )

    return "\n".join(lines)


def gather_metrics(client: PostHogClient, window_days: int) -> tuple[dict, list[str]]:
    errors: list[str] = []
    metrics: dict = {}

    # Homepage views — match $pageview where pathname is "/" or trailing slash.
    rows, err = safe_query(
        client,
        f"""
        SELECT count()
        FROM events
        WHERE event = '$pageview'
          AND properties.$pathname IN ('/', '')
          AND timestamp >= now() - INTERVAL {window_days} DAY
        """,
    )
    if err:
        errors.append(f"homepage_pageviews: {err}")
    metrics["homepage_pageviews"] = fmt_count(rows)

    # Waitlist views.
    rows, err = safe_query(
        client,
        f"""
        SELECT count()
        FROM events
        WHERE event = '$pageview'
          AND properties.$pathname IN ('/waitlist', '/waitlist/')
          AND timestamp >= now() - INTERVAL {window_days} DAY
        """,
    )
    if err:
        errors.append(f"waitlist_pageviews: {err}")
    metrics["waitlist_pageviews"] = fmt_count(rows)

    # Signups.
    rows, err = safe_query(
        client,
        f"""
        SELECT count()
        FROM events
        WHERE event = 'waitlist_signed_up'
          AND timestamp >= now() - INTERVAL {window_days} DAY
        """,
    )
    if err:
        errors.append(f"signups: {err}")
    metrics["signups"] = fmt_count(rows)

    # Duplicates.
    rows, err = safe_query(
        client,
        f"""
        SELECT count()
        FROM events
        WHERE event = 'waitlist_signup_duplicate'
          AND timestamp >= now() - INTERVAL {window_days} DAY
        """,
    )
    if err:
        errors.append(f"duplicate_signups: {err}")
    metrics["duplicate_signups"] = fmt_count(rows)

    # Referral-attributed signups.
    rows, err = safe_query(
        client,
        f"""
        SELECT count()
        FROM events
        WHERE event = 'referral_link_used'
          AND timestamp >= now() - INTERVAL {window_days} DAY
        """,
    )
    if err:
        errors.append(f"referral_signups: {err}")
    metrics["referral_signups"] = fmt_count(rows)

    # Share-clicked total + by channel.
    rows, err = safe_query(
        client,
        f"""
        SELECT properties.channel AS channel, count() AS n
        FROM events
        WHERE event = 'share_clicked'
          AND timestamp >= now() - INTERVAL {window_days} DAY
        GROUP BY properties.channel
        """,
    )
    if err:
        errors.append(f"share_clicks_by_channel: {err}")
    by_channel: dict[str, int] = {}
    for row in rows:
        if not row:
            continue
        channel = (row[0] or "unknown").strip().lower()
        by_channel[channel] = int(row[1] or 0)
    metrics["share_clicks_by_channel"] = by_channel
    metrics["share_clicks_total"] = sum(by_channel.values())

    rows, err = safe_query(
        client,
        f"""
        SELECT count()
        FROM events
        WHERE event = 'share_copy_succeeded'
          AND timestamp >= now() - INTERVAL {window_days} DAY
        """,
    )
    if err:
        errors.append(f"share_copy_succeeded: {err}")
    metrics["share_copy_succeeded"] = fmt_count(rows)

    rows, err = safe_query(
        client,
        f"""
        SELECT count()
        FROM events
        WHERE event = 'share_native_completed'
          AND timestamp >= now() - INTERVAL {window_days} DAY
        """,
    )
    if err:
        errors.append(f"share_native_completed: {err}")
    metrics["share_native_completed"] = fmt_count(rows)

    return metrics, errors


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--window", default=DEFAULT_WINDOW, help="e.g. 7d, 30d (default 30d)")
    parser.add_argument("--focus", choices=["share"], default=None)
    parser.add_argument("--out", default=None, help="Output path (default .tmp/metrics-{date}.md)")
    args = parser.parse_args(argv)

    window_days = parse_window(args.window)

    env = load_env(ENV_PATH)
    api_key = os.environ.get("POSTHOG_PERSONAL_API_KEY") or env.get("POSTHOG_PERSONAL_API_KEY")
    project_id = os.environ.get("POSTHOG_PROJECT_ID") or env.get("POSTHOG_PROJECT_ID")
    host = os.environ.get("POSTHOG_HOST") or env.get("POSTHOG_HOST") or DEFAULT_HOST

    out_path = Path(args.out) if args.out else (
        PROJECT_ROOT / ".tmp" / f"metrics-{_dt.date.today().isoformat()}.md"
    )
    out_path.parent.mkdir(parents=True, exist_ok=True)

    if not api_key or not project_id:
        report = render_report(
            window_days,
            args.focus,
            {"_unavailable": True},
            ["POSTHOG_PERSONAL_API_KEY or POSTHOG_PROJECT_ID missing from .env"],
        )
        out_path.write_text(report, encoding="utf-8")
        print(out_path)
        return 0

    client = PostHogClient(host, project_id, api_key)
    metrics, errors = gather_metrics(client, window_days)

    # If literally every query failed, mark unavailable so workflows know.
    if metrics.get("homepage_pageviews", 0) == 0 and metrics.get("signups", 0) == 0 and len(errors) >= 5:
        metrics["_unavailable"] = True

    report = render_report(window_days, args.focus, metrics, errors)
    out_path.write_text(report, encoding="utf-8")
    print(out_path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
