#!/usr/bin/env python3
"""
Bundle live site HTML + brand context + latest qualitative feedback into a
single markdown snapshot. Consumed by the conversion-audit and
viral-coefficient-audit workflows.

Usage:
    python tools/site_snapshot.py
    python tools/site_snapshot.py --out .tmp/snapshot-2026-05-02.md

Writes by default to .tmp/snapshot-{YYYY-MM-DD}.md and prints the path on
stdout.

No third-party deps — stdlib only. Run from the project root.
"""
from __future__ import annotations

import argparse
import csv
import datetime as _dt
import os
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent

# Files to bundle. Order matters — it's the structure of the output document.
HTML_PAGES = [
    ("Homepage (`/`)", "index.html"),
    ("Waitlist (`/waitlist`)", "waitlist/index.html"),
]

CONTEXT_DOCS = [
    ("Project context", "context.md"),
    ("Manifesto", "manifesto.md"),
    ("Four-layers philosophy", "four-layers-philosophy.md"),
    ("Style guide", "style-guide.md"),
    ("Brand guardrails", "workflows/brand-guardrails.md"),
]

# Anything matching one of these globs at the project root that *also* contains
# the word "feedback" (case-insensitive). Picks up the original
# "Haven - Launch feedback _ iterations - Sheet1.csv" plus any future feedback
# CSVs without needing this file edited.
FEEDBACK_PATTERNS = ["*feedback*.csv", "*feedback*.md", "*launch*.csv"]


def read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return f"_(file not found: {path})_"
    except UnicodeDecodeError:
        return path.read_text(encoding="latin-1")


def csv_to_markdown_table(path: Path) -> str:
    """Render a small CSV as a markdown table. Truncates if too long."""
    rows = []
    with path.open(newline="", encoding="utf-8") as f:
        reader = csv.reader(f)
        for row in reader:
            rows.append(row)
    if not rows:
        return "_(empty CSV)_"
    header, body = rows[0], rows[1:]
    out = []
    out.append("| " + " | ".join(_md_cell(c) for c in header) + " |")
    out.append("| " + " | ".join("---" for _ in header) + " |")
    for row in body:
        # Pad short rows to header length.
        row = row + [""] * (len(header) - len(row))
        out.append("| " + " | ".join(_md_cell(c) for c in row[: len(header)]) + " |")
    return "\n".join(out)


def _md_cell(value: str) -> str:
    """Make a CSV cell safe to drop in a markdown table cell."""
    return value.replace("|", "\\|").replace("\n", " <br> ").strip()


def find_feedback_files(root: Path) -> list[Path]:
    found: set[Path] = set()
    for pattern in FEEDBACK_PATTERNS:
        for p in root.glob(pattern):
            if "feedback" in p.name.lower() or "launch" in p.name.lower():
                found.add(p)
    return sorted(found)


def fence(language: str, content: str) -> str:
    """Wrap content in a code fence, escaping any nested triple-backticks."""
    safe = content.replace("```", "``​`")
    return f"```{language}\n{safe}\n```"


def build_snapshot() -> str:
    today = _dt.date.today().isoformat()
    parts: list[str] = []
    parts.append(f"# Site Snapshot — {today}\n")
    parts.append(
        "Generated by `tools/site_snapshot.py`. Consumed by the auto-research "
        "audit workflows in `workflows/`.\n"
    )

    parts.append("\n---\n\n## Live HTML\n")
    for title, rel in HTML_PAGES:
        path = PROJECT_ROOT / rel
        parts.append(f"\n### {title} — `{rel}`\n")
        parts.append(fence("html", read_text(path)))

    parts.append("\n---\n\n## Brand context\n")
    for title, rel in CONTEXT_DOCS:
        path = PROJECT_ROOT / rel
        parts.append(f"\n### {title} — `{rel}`\n")
        if path.exists():
            parts.append(fence("markdown", read_text(path)))
        else:
            parts.append(f"_(missing: {rel})_\n")

    parts.append("\n---\n\n## Latest qualitative feedback\n")
    feedback_files = find_feedback_files(PROJECT_ROOT)
    if not feedback_files:
        parts.append(
            "_(no feedback files found — looked for patterns: "
            f"{', '.join(FEEDBACK_PATTERNS)})_\n"
        )
    else:
        for path in feedback_files:
            parts.append(f"\n### `{path.name}`\n")
            if path.suffix.lower() == ".csv":
                parts.append(csv_to_markdown_table(path))
                parts.append("\n")
            else:
                parts.append(fence("markdown", read_text(path)))

    parts.append(
        "\n---\n\n*End of snapshot.*  Audit workflows should treat the live "
        "HTML as the authoritative current state — this file is a frozen "
        "copy for reproducibility.\n"
    )

    return "\n".join(parts)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        default=None,
        help="Output path. Defaults to .tmp/snapshot-{YYYY-MM-DD}.md.",
    )
    args = parser.parse_args(argv)

    out_path = Path(args.out) if args.out else (
        PROJECT_ROOT / ".tmp" / f"snapshot-{_dt.date.today().isoformat()}.md"
    )
    out_path.parent.mkdir(parents=True, exist_ok=True)

    snapshot = build_snapshot()
    out_path.write_text(snapshot, encoding="utf-8")

    print(out_path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
